import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "en": {
      "Select Languages": "Select Languages",
      "Save": "Save",
      "All Languages Voice Dictionary": "All Languages Voice Dictionary",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary",
      "Skip": "Skip",
      "Next": "Next",
      "Instant Translation": "Instant Translation",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds",
      "Save Words": "Save Words",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary",
      "Get Started": "Get Started",
      "ALL LANGUAGES DICTIONARY": "ALL LANGUAGES DICTIONARY",
      "English": "English",
      "Urdu": "Urdu",
      "Write Something": "Write Something",
      "Features": "Features",
      "View All": "View All",
      "Translations": "Translations",
      "History": "History",
      "Share": "Share",
      "Home": "Home",
      "Setting": "Setting",
      "Favourites": "Favourites",
      "No Favourites available": "No Favourites available",
      "No history available": "No history available"
    },
    "af": {
  "Are you sure you want to delete?": "Is jy seker jy wil verwyder?",
  "No": "Nee",
  "Yes": "Ja",
  "Delete": "Verwyder",
      "Select Languages": "Kies Tale",
      "Save": "Stoor",
      "All Languages Voice Dictionary": "Alle Tale Stemwoordeboek",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "Ontdek woorde betekenis, hoor akkurate uitspraak en brei jou woordeboek uit met ons stemwoordeboek",
      "Skip": "Slaan oor",
      "Next": "Volgende",
      "Instant Translation": "Onmiddellike Vertaling",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "Ons Vertaalfunksie maak dit eenvoudig om taal te verstaan en te leer. Voer net jou teks in en kry 'n duidelike vertaling binne sekondes",
      "Save Words": "Stoor Woorde",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "Stoor en organiseer maklik woorde wat jy wil leer. Ons funksie laat jou toe om jou eie persoonlike woordeboek te bou",
      "Get Started": "Begin Nou",
      "ALL LANGUAGES DICTIONARY": "ALLE TALE WOORDEBOEK",
      "English": "Engels",
      "Urdu": "Oerdoe",
      "Write Something...": "Skryf Iets",
      "Features": "Kenmerke",
      "View all": "Sien Alles",
      "Translations": "Vertalings",
      "History": "Geskiedenis",
      "Share": "Deel",
      "Home": "Tuis",
      "Settings": "Instelling",
      "Favourites": "Gunstelinge",
      "No Favourites available": "Geen Gunstelinge beskikbaar nie",
      "No history available": "Geen Geskiedenis beskikbaar nie",
      "apple": "appel",
      "banana": "piesang",
      "cherry": "kersie",
      "date": "dati",
      "elderberry": "vlierbes",
      "fig": "vy",
      "grape": "druif",
      "honeydew": "honeydew",
      "orange": "lemoen",
      "queen": "koningin",
      "kingdom": "koninkryk",
      "viking": "viking",
      "Are you sure to exit from App?": "Is jy seker jy wil die app verlaat?",
      "Yes": "Ja",
      "No": "Nee",
      "Write Something....":"skryf iets",
      "Notificatins":"kennisgewings",
    },
    "ar": {
  "Are you sure you want to delete?": "هل أنت متأكد أنك تريد الحذف؟",
  "No": "لا",
  "Yes": "نعم",
  "Delete": "حذف",
  "apple": "تفاح",
  "banana": "موز",
  "cherry": "كرز",
  "date": "تمر",
  "elderberry": "زهر العطاس",
  "fig": "تين",
  "grape": "عنب",
  "honeydew": "شمام",
  "orange": "برتقال",
  "queen": "ملكة",
  "kingdom": "مملكة",
  "viking": "فايكنج",
  "Exit App": "خروج من التطبيق",
  "Are you sure to exit from App?": "هل أنت متأكد أنك تريد الخروج من التطبيق؟",
  "Yes": "نعم",
  "No": "لا",
      "Select Languages": "اختر اللغات",
      "Save": "حفظ",
      "All Languages Voice Dictionary": "قاموس الصوت لجميع اللغات",
      "ALL LANGUAGES DICTIONARY": "قاموس الصوت لجميع اللغات",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "اكتشف معاني الكلمات، اسمع النطق الدقيق، ووسع قاموسك مع قاموس الصوت الخاص بنا",
      "Skip": "تخطي",
      "Next": "التالي",
      "Instant Translation": "ترجمة فورية",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "تتيح لك ميزة الترجمة الخاصة بنا فهم اللغة وتعلمها ببساطة. ما عليك سوى إدخال نصك والحصول على ترجمة واضحة في ثوانٍ",
      "Save Words": "احفظ الكلمات",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "احفظ ونظم الكلمات التي تريد تعلمها بسهولة. تتيح لك ميزتنا بناء قاموسك الشخصي",
      "Get Started": "ابدأ الآن",
      "ALL LANGUAGES DICTIONARY": "قاموس جميع اللغات",
      "English": "الإنجليزية",
      "Urdu": "الأردية",
      "Write Something...": "اكتب شيئًا",
      "Features": "الميزات",
      "View all": "عرض الكل",
      "Translations": "الترجمات",
      "History": "التاريخ",
      "Share": "مشاركة",
      "Home": "الصفحة الرئيسية",
      "Setting": "الإعدادات",
      "Favourites": "المفضلة",
      "No Favorites available": "لا توجد مفضلات",
      "No history available": "لا يوجد سجل",
      "Settings":"إعدادات",
      "Notifications":"إشعارات",
      "Write Something....":"أكتب شيئا",
    },
    "zh": {
  "Are you sure you want to delete?": "你确定要删除吗？",
  "No": "不",
  "Yes": "是",
  "Delete": "删除",
  "apple": "苹果",
  "banana": "香蕉",
  "cherry": "樱桃",
  "date": "枣",
  "elderberry": "接骨木莓",
  "fig": "无花果",
  "grape": "葡萄",
  "honeydew": "蜜露",
  "orange": "橙子",
  "queen": "女王",
  "kingdom": "王国",
  "viking": "维京",
  "Exit App": "退出应用",
  "Are you sure to exit from App?": "您确定要退出应用吗？",
  "Yes": "是",
  "No": "否",
      "Select Languages": "选择语言",
      "Save": "保存",
      "All Languages Voice Dictionary": "所有语言语音词典",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "发现单词含义，听准确发音，并使用我们的语音词典扩展您的词汇表",
      "Skip": "跳过",
      "Next": "下一个",
      "Instant Translation": "即时翻译",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "我们的翻译功能让您轻松理解和学习语言。只需输入您的文本，即可在几秒钟内获得清晰的翻译",
      "Save Words": "保存单词",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "轻松保存和组织您想学习的单词。我们的功能允许您建立自己的个人词典",
      "Get Started": "开始使用",
      "ALL LANGUAGES DICTIONARY": "所有语言词典",
      "English": "英语",
      "Urdu": "乌尔都语",
      "Write Something....": "写点东西",
      "Features": "功能",
      "View All": "查看全部",
      "Translations": "翻译",
      "History": "历史记录",
      "Share": "分享",
      "Home": "首页",
      "Setting": "设置",
      "Favourites": "收藏夹",
      "No Favourites available": "没有可用的收藏",
      "No history available": "没有可用的历史记录"
    },
    "cs": {
  "Are you sure you want to delete?": "Opravdu chcete smazat?",
  "No": "Ne",
  "Yes": "Ano",
  "Delete": "Smazat",
  "apple": "jablko",
  "banana": "banán",
  "cherry": "třešeň",
  "date": "datle",
  "elderberry": "sambucus",
  "fig": "fíkovník",
  "grape": "hroznové víno",
  "honeydew": "medový meloun",
  "orange": "pomeranč",
  "queen": "královna",
  "kingdom": "království",
  "viking": "viking",
  "Exit App": "Ukončit aplikaci",
  "Are you sure to exit from App?": "Opravdu chcete aplikaci ukončit?",
  "Yes": "Ano",
  "No": "Ne",
      "Select Languages": "Vyberte Jazyky",
      "Save": "Uložit",
      "All Languages Voice Dictionary": "Hlasový Slovník Všech Jazyků",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "Objevte význam slov, slyšte přesnou výslovnost a rozšiřte svůj slovník pomocí našeho hlasového slovníku",
      "Skip": "Přeskočit",
      "Next": "Další",
      "Instant Translation": "Okamžitý Překlad",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "Naše funkce překladu vám umožňuje snadno porozumět a učit se jazyk. Stačí zadat text a během několika sekund získat jasný překlad",
      "Save Words": "Uložit Slova",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "Snadno ukládejte a organizujte slova, která se chcete naučit. Naše funkce vám umožňuje vytvářet vlastní osobní slovník",
      "Get Started": "Začít",
      "ALL LANGUAGES DICTIONARY": "SLOVNÍK VŠECH JAZYKŮ",
      "English": "Angličtina",
      "Urdu": "Urdu",
      "Write Something....": "Napište Něco",
      "Features": "Funkce",
      "View All": "Zobrazit Vše",
      "Translations": "Překlady",
      "History": "Historie",
      "Share": "Sdílet",
      "Home": "Domů",
      "Setting": "Nastavení",
      "Favourites": "Oblíbené",
      "No Favourites available": "Nejsou K Dispozici Žádné Oblíbené",
      "No history available": "Není K Dispozici Žádná Historie"
    },
    "da": {
  "Are you sure you want to delete?": "Er du sikker på, at du vil slette?",
  "No": "Nej",
  "Yes": "Ja",
  "Delete": "Slet",
  "apple": "æble",
  "banana": "banan",
  "cherry": "kirsebær",
  "date": "daddel",
  "elderberry": "hyldebær",
  "fig": "figner",
  "grape": "drue",
  "honeydew": "honningmelon",
  "orange": "appelsin",
  "queen": "dronning",
  "kingdom": "kongerige",
  "viking": "viking",
  "Exit App": "Afslut app",
  "Are you sure to exit from App?": "Er du sikker på, at du vil afslutte appen?",
  "Yes": "Ja",
  "No": "Nej",
      "Select Languages": "Vælg Sprog",
      "Save": "Gem",
      "All Languages Voice Dictionary": "Alle Sprog Stemmeordbog",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "Opdag ords betydning, hør præcis udtale, og udvid dit ordbog med vores stemmeordbog",
      "Skip": "Spring Over",
      "Next": "Næste",
      "Instant Translation": "Øjeblikkelig Oversættelse",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "Vores oversættelsesfunktion gør det enkelt at forstå og lære sprog. Indtast blot din tekst og få en klar oversættelse på få sekunder",
      "Save Words": "Gem Ord",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "Gem og organiser nemt ord, du vil lære. Vores funktion giver dig mulighed for at oprette din egen personlige ordbog",
      "Get Started": "Kom I Gang",
      "ALL LANGUAGES DICTIONARY": "ALLE SPROG ORDBOG",
      "English": "Engelsk",
      "Urdu": "Urdu",
      "Write Something....": "Skriv Noget",
      "Features": "Funktioner",
      "View All": "Se Alle",
      "Translations": "Oversættelser",
      "History": "Historik",
      "Share": "Del",
      "Home": "Hjem",
      "Setting": "Indstilling",
      "Favourites": "Favoritter",
      "No Favourites available": "Ingen Favoritter Tilgængelige",
      "No history available": "Ingen Historik Tilgængelig"
    },
    "nl": {
  "Are you sure you want to delete?": "Weet je zeker dat je wilt verwijderen?",
  "No": "Nee",
  "Yes": "Ja",
  "Delete": "Verwijderen",
  "apple": "appel",
  "banana": "banaan",
  "cherry": "kers",
  "date": "dadel",
  "elderberry": "vlierbes",
  "fig": "vijg",
  "grape": "druif",
  "honeydew": "honingdauw",
  "orange": "sinaasappel",
  "queen": "koningin",
  "kingdom": "koninkrijk",
  "viking": "viking",
  "Exit App": "Verlaat app",
  "Are you sure to exit from App?": "Weet je zeker dat je de app wilt verlaten?",
  "Yes": "Ja",
  "No": "Nee",
      "Select Languages": "Selecteer Talen",
      "Save": "Opslaan",
      "All Languages Voice Dictionary": "Alle Talen Stem Woordenboek",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "Ontdek de betekenis van woorden, hoor de juiste uitspraak en breid je woordenboek uit met ons stemwoordenboek",
      "Skip": "Overslaan",
      "Next": "Volgende",
      "Instant Translation": "Directe Vertaling",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "Met onze vertaalfunctie kunt u eenvoudig taal begrijpen en leren. Voer gewoon uw tekst in en krijg binnen enkele seconden een duidelijke vertaling",
      "Save Words": "Woorden Opslaan",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "Sla eenvoudig woorden op en organiseer ze die u wilt leren. Onze functie stelt u in staat uw eigen persoonlijke woordenboek op te bouwen",
      "Get Started": "Begin Nu",
      "ALL LANGUAGES DICTIONARY": "ALLE TALEN WOORDENBOEK",
      "English": "Engels",
      "Urdu": "Urdu",
      "Write Something....": "Schrijf Iets",
      "Features": "Functies",
      "View All": "Bekijk Alles",
      "Translations": "Vertalingen",
      "History": "Geschiedenis",
      "Share": "Delen",
      "Home": "Home",
      "Setting": "Instelling",
      "Favourites": "Favorieten",
      "No Favourites available": "Geen Favorieten Beschikbaar",
      "No history available": "Geen Geschiedenis Beschikbaar"
    },
    "fr": {
  "Are you sure you want to delete?": "Êtes-vous sûr de vouloir supprimer ?",
  "No": "Non",
  "Yes": "Oui",
  "Delete": "Supprimer",
  "apple": "pomme",
  "banana": "banane",
  "cherry": "cerise",
  "date": "date",
  "elderberry": "sureau",
  "fig": "figue",
  "grape": "raisin",
  "honeydew": "melon miel",
  "orange": "orange",
  "queen": "reine",
  "kingdom": "royaume",
  "viking": "viking",
  "Exit App": "Quitter l'application",
  "Are you sure to exit from App?": "Êtes-vous sûr de vouloir quitter l'application ?",
  "Yes": "Oui",
  "No": "Non",
      "Select Languages": "Sélectionner Les Langues",
      "Save": "Enregistrer",
      "All Languages Voice Dictionary": "Dictionnaire Vocal De Toutes Les Langues",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "Découvrez la signification des mots, écoutez la prononciation correcte et enrichissez votre dictionnaire avec notre dictionnaire vocal",
      "Skip": "Passer",
      "Next": "Suivant",
      "Instant Translation": "Traduction Instantanée",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "Notre fonction de traduction vous permet de comprendre et d'apprendre facilement une langue. Entrez simplement votre texte et obtenez une traduction claire en quelques secondes",
      "Save Words": "Enregistrer Les Mots",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "Enregistrez et organisez facilement les mots que vous souhaitez apprendre. Notre fonctionnalité vous permet de créer votre propre dictionnaire personnel",
      "Get Started": "Commencer",
      "ALL LANGUAGES DICTIONARY": "DICTIONNAIRE TOUTES LES LANGUES",
      "English": "Anglais",
      "Urdu": "Ourdou",
      "Write Something....": "Écrire Quelque Chose",
      "Features": "Caractéristiques",
      "View All": "Voir Tout",
      "Translations": "Traductions",
      "History": "Historique",
      "Share": "Partager",
      "Home": "Accueil",
      "Setting": "Paramètre",
      "Favourites": "Favoris",
      "No Favourites available": "Aucun Favori Disponible",
      "No history available": "Aucun Historique Disponible"
    },
    "de": {
  "Are you sure you want to delete?": "Sind Sie sicher, dass Sie löschen möchten?",
  "No": "Nein",
  "Yes": "Ja",
  "Delete": "Löschen",
  "apple": "Apfel",
  "banana": "Banane",
  "cherry": "Kirsche",
  "date": "Dattel",
  "elderberry": "Holunderbeere",
  "fig": "Feige",
  "grape": "Traube",
  "honeydew": "Honigmelone",
  "orange": "Orange",
  "queen": "Königin",
  "kingdom": "Königreich",
  "viking": "Wikinger",
  "Exit App": "App beenden",
  "Are you sure to exit from App?": "Sind Sie sicher, dass Sie die App beenden möchten?",
  "Yes": "Ja",
  "No": "Nein",
      "Select Languages": "Sprachen Wählen",
      "Save": "Speichern",
      "All Languages Voice Dictionary": "Alle Sprachen Sprachwörterbuch",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "Entdecken Sie die Bedeutung von Wörtern, hören Sie die genaue Aussprache und erweitern Sie Ihr Wörterbuch mit unserem Sprachwörterbuch",
      "Skip": "Überspringen",
      "Next": "Weiter",
      "Instant Translation": "Sofortige Übersetzung",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "Mit unserer Übersetzungsfunktion können Sie die Sprache einfach verstehen und lernen. Geben Sie einfach Ihren Text ein und erhalten Sie in Sekunden eine klare Übersetzung",
      "Save Words": "Wörter Speichern",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "Speichern und organisieren Sie einfach die Wörter, die Sie lernen möchten. Mit unserer Funktion können Sie Ihr eigenes persönliches Wörterbuch erstellen",
      "Get Started": "Loslegen",
      "ALL LANGUAGES DICTIONARY": "ALLE SPRACHEN WÖRTERBUCH",
      "English": "Englisch",
      "Urdu": "Urdu",
      "Write Something....": "Schreiben Sie Etwas",
      "Features": "Funktionen",
      "View All": "Alle Anzeigen",
      "Translations": "Übersetzungen",
      "History": "Verlauf",
      "Share": "Teilen",
      "Home": "Startseite",
      "Setting": "Einstellung",
      "Favourites": "Favoriten",
      "No Favourites available": "Keine Favoriten Verfügbar",
      "No history available": "Kein Verlauf Verfügbar"
    },
    "el": {
  "Are you sure you want to delete?": "Είστε σίγουροι ότι θέλετε να διαγράψετε;",
  "No": "Όχι",
  "Yes": "Ναι",
  "Delete": "Διαγραφή",
  "apple": "μήλο",
  "banana": "μπανάνα",
  "cherry": "κεράσι",
  "date": "χουρμάς",
  "elderberry": "γιούνκα",
  "fig": "συκώτι",
  "grape": "σταφύλι",
  "honeydew": "μέλι-πεπόνι",
  "orange": "πορτοκάλι",
  "queen": "βασίλισσα",
  "kingdom": "βασίλειο",
  "viking": "Βίκινγκ",
  "Exit App": "Έξοδος από την εφαρμογή",
  "Are you sure to exit from App?": "Είστε σίγουροι ότι θέλετε να βγείτε από την εφαρμογή;",
  "Yes": "Ναι",
  "No": "Όχι",
      "Select Languages": "Επιλογή Γλωσσών",
      "Save": "Αποθήκευση",
      "All Languages Voice Dictionary": "Λεξικό Φωνής Όλων Των Γλωσσών",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "Ανακαλύψτε τη σημασία των λέξεων, ακούστε ακριβή προφορά και επεκτείνετε το λεξικό σας με το λεξικό φωνής μας",
      "Skip": "Παράλειψη",
      "Next": "Επόμενο",
      "Instant Translation": "Άμεση Μετάφραση",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "Η λειτουργία μετάφρασής μας καθιστά απλή την κατανόηση και εκμάθηση της γλώσσας. Απλά εισαγάγετε το κείμενό σας και λάβετε μια σαφή μετάφραση σε δευτερόλεπτα",
      "Save Words": "Αποθήκευση Λέξεων",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "Αποθηκεύστε και οργανώστε εύκολα τις λέξεις που θέλετε να μάθετε. Η λειτουργία μας σας επιτρέπει να δημιουργήσετε το δικό σας προσωπικό λεξικό",
      "Get Started": "Ξεκινήστε",
      "ALL LANGUAGES DICTIONARY": "ΛΕΞΙΚΟ ΟΛΩΝ ΤΩΝ ΓΛΩΣΣΩΝ",
      "English": "Αγγλικά",
      "Urdu": "Ουρντού",
      "Write Something....": "Γράψτε Κάτι",
      "Features": "Χαρακτηριστικά",
      "View All": "Δείτε Όλα",
      "Translations": "Μεταφράσεις",
      "History": "Ιστορικό",
      "Share": "Κοινοποίηση",
      "Home": "Αρχική Σελίδα",
      "Setting": "Ρύθμιση",
      "Favourites": "Αγαπημένα",
      "No Favourites available": "Δεν Υπάρχουν Αγαπημένα",
      "No history available": "Δεν Υπάρχει Ιστορικό"
    },
    "hi": {
  "Are you sure you want to delete?": "क्या आप सुनिश्चित हैं कि आप इसे हटाना चाहते हैं?",
  "No": "नहीं",
  "Yes": "हाँ",
  "Delete": "हटाएँ",
  "apple": "सेब",
  "banana": "केला",
  "cherry": "चेरी",
  "date": "खजूर",
  "elderberry": "एlderberry",
  "fig": "अंजीर",
  "grape": "अंगूर",
  "honeydew": "हनीड्यू",
  "orange": "संतरा",
  "queen": "रानी",
  "kingdom": "राज्य",
  "viking": "वाइकिंग",
  "Exit App": "ऐप से बाहर निकलें",
  "Are you sure to exit from App?": "क्या आप वाकई ऐप से बाहर निकलना चाहते हैं?",
  "Yes": "हाँ",
  "No": "नहीं",
      "Select Languages": "भाषाएँ चुनें",
      "Save": "सहेजें",
      "All Languages Voice Dictionary": "सभी भाषाओं का वॉयस शब्दकोश",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "शब्दों का अर्थ खोजें, सही उच्चारण सुनें, और हमारे वॉयस शब्दकोश के साथ अपने शब्दकोश का विस्तार करें",
      "Skip": "छोड़ें",
      "Next": "अगला",
      "Instant Translation": "तत्काल अनुवाद",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "हमारी अनुवाद सुविधा भाषा को समझने और सीखने को सरल बनाती है। बस अपना पाठ दर्ज करें और कुछ ही सेकंड में स्पष्ट अनुवाद प्राप्त करें",
      "Save Words": "शब्द सहेजें",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "आसानी से उन शब्दों को सहेजें और व्यवस्थित करें जिन्हें आप सीखना चाहते हैं। हमारी सुविधा आपको अपना व्यक्तिगत शब्दकोश बनाने देती है",
      "Get Started": "शुरू करें",
      "ALL LANGUAGES DICTIONARY": "सभी भाषाओं का शब्दकोश",
      "English": "अंग्रेज़ी",
      "Urdu": "उर्दू",
      "Write Something....": "कुछ लिखें",
      "Features": "विशेषताएँ",
      "View All": "सभी देखें",
      "Translations": "अनुवाद",
      "History": "इतिहास",
      "Share": "साझा करें",
      "Home": "होम",
      "Setting": "सेटिंग",
      "Favourites": "पसंदीदा",
      "No Favourites available": "कोई पसंदीदा उपलब्ध नहीं",
      "No history available": "कोई इतिहास उपलब्ध नहीं"
    },
    "id": {
  "Are you sure you want to delete?": "Apakah Anda yakin ingin menghapus?",
  "No": "Tidak",
  "Yes": "Ya",
  "Delete": "Hapus",
  "apple": "apel",
  "banana": "pisang",
  "cherry": "ceri",
  "date": "kurma",
  "elderberry": "beri elder",
  "fig": "ara",
  "grape": "anggur",
  "honeydew": "melonn madu",
  "orange": "jeruk",
  "queen": "ratu",
  "kingdom": "kerajaan",
  "viking": "viking",
  "Exit App": "Keluar Aplikasi",
  "Are you sure to exit from App?": "Apakah Anda yakin ingin keluar dari aplikasi?",
  "Yes": "Ya",
  "No": "Tidak",
      "Select Languages": "Pilih Bahasa",
      "Save": "Simpan",
      "All Languages Voice Dictionary": "Kamus Suara Semua Bahasa",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "Temukan arti kata, dengar pelafalan yang akurat, dan perluas kamus Anda dengan kamus suara kami",
      "Skip": "Lewati",
      "Next": "Berikutnya",
      "Instant Translation": "Terjemahan Instan",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "Fitur terjemahan kami membuatnya mudah untuk memahami dan belajar bahasa. Cukup masukkan teks Anda dan dapatkan terjemahan yang jelas dalam hitungan detik",
      "Save Words": "Simpan Kata",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "Dengan mudah menyimpan dan mengatur kata-kata yang ingin Anda pelajari. Fitur kami memungkinkan Anda untuk membuat kamus pribadi Anda sendiri",
      "Get Started": "Mulai",
      "ALL LANGUAGES DICTIONARY": "KAMUS SEMUA BAHASA",
      "English": "Bahasa Inggris",
      "Urdu": "Urdu",
      "Write Something....": "Tulis Sesuatu",
      "Features": "Fitur",
      "View All": "Lihat Semua",
      "Translations": "Terjemahan",
      "History": "Riwayat",
      "Share": "Bagikan",
      "Home": "Beranda",
      "Setting": "Pengaturan",
      "Favourites": "Favorit",
      "No Favourites available": "Tidak Ada Favorit Tersedia",
      "No history available": "Tidak Ada Riwayat Tersedia"
    },
    "it": {
  "Are you sure you want to delete?": "Sei sicuro di voler eliminare?",
  "No": "No",
  "Yes": "Sì",
  "Delete": "Elimina",
  "apple": "mela",
  "banana": "banana",
  "cherry": "ciliegia",
  "date": "dattero",
  "elderberry": "sambuco",
  "fig": "fico",
  "grape": "uva",
  "honeydew": "melone",
  "orange": "arancia",
  "queen": "regina",
  "kingdom": "regno",
  "viking": "vichingo",
  "Exit App": "Esci dall'app",
  "Are you sure to exit from App?": "Sei sicuro di voler uscire dall'app?",
  "Yes": "Sì",
  "No": "No",
      "Select Languages": "Seleziona Lingue",
      "Save": "Salva",
      "All Languages Voice Dictionary": "Dizionario Vocale Di Tutte Le Lingue",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "Scopri il significato delle parole, ascolta la pronuncia corretta ed espandi il tuo vocabolario con il nostro dizionario vocale",
      "Skip": "Salta",
      "Next": "Avanti",
      "Instant Translation": "Traduzione Istantanea",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "La nostra funzione di traduzione rende semplice comprendere e imparare la lingua. Inserisci il tuo testo e ottieni una traduzione chiara in pochi secondi",
      "Save Words": "Salva Parole",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "Salva e organizza facilmente le parole che desideri imparare. La nostra funzione ti consente di creare il tuo dizionario personale",
      "Get Started": "Inizia",
      "ALL LANGUAGES DICTIONARY": "DIZIONARIO DI TUTTE LE LINGUE",
      "English": "Inglese",
      "Urdu": "Urdu",
      "Write Something....": "Scrivi Qualcosa",
      "Features": "Caratteristiche",
      "View All": "Vedi Tutto",
      "Translations": "Traduzioni",
      "History": "Cronologia",
      "Share": "Condividi",
      "Home": "Home",
      "Setting": "Impostazione",
      "Favourites": "Preferiti",
      "No Favourites available": "Nessun Preferito Disponibile",
      "No history available": "Nessuna Cronologia Disponibile"
    },
    "ja": {
  "Are you sure you want to delete?": "本当に削除してもよろしいですか？",
  "No": "いいえ",
  "Yes": "はい",
  "Delete": "削除",
  "apple": "リンゴ",
  "banana": "バナナ",
  "cherry": "さくらんぼ",
  "date": "デーツ",
  "elderberry": "ニワトコ",
  "fig": "イチジク",
  "grape": "ぶどう",
  "honeydew": "ハニーデュー",
  "orange": "オレンジ",
  "queen": "女王",
  "kingdom": "王国",
  "viking": "バイキング",
  "Exit App": "アプリを終了する",
  "Are you sure to exit from App?": "アプリを終了してもよろしいですか？",
  "Yes": "はい",
  "No": "いいえ",
      "Select Languages": "言語を選択",
      "Save": "保存する",
      "All Languages Voice Dictionary": "すべての言語の音声辞書",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "言葉の意味を見つけ、正確な発音を聞き、私たちの音声辞書であなたの辞書を拡大してください",
      "Skip": "スキップ",
      "Next": "次へ",
      "Instant Translation": "瞬間翻訳",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "私たちの翻訳機能を使用すると、言語を簡単に理解し学ぶことができます。 テキストを入力するだけで、数秒で明確な翻訳が得られます",
      "Save Words": "単語を保存する",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "学びたい言葉を簡単に保存して整理できます。 この機能を使用すると、自分だけの個人的な辞書を作成できます",
      "Get Started": "始める",
      "ALL LANGUAGES DICTIONARY": "すべての言語の辞書",
      "English": "英語",
      "Urdu": "ウルドゥー語",
      "Write Something....": "何かを書く",
      "Features": "特徴",
      "View All": "すべてを見る",
      "Translations": "翻訳",
      "History": "歴史",
      "Share": "共有",
      "Home": "ホーム",
      "Setting": "設定",
      "Favourites": "お気に入り",
      "No Favourites available": "お気に入りはありません",
      "No history available": "履歴はありません"
    },
    "ko": {
  "Are you sure you want to delete?": "정말로 삭제하시겠습니까?",
  "No": "아니요",
  "Yes": "예",
  "Delete": "삭제",
  "apple": "사과",
  "banana": "바나나",
  "cherry": "체리",
  "date": "대추",
  "elderberry": "엘더베리",
  "fig": "무화과",
  "grape": "포도",
  "honeydew": "허니듀",
  "orange": "오렌지",
  "queen": "여왕",
  "kingdom": "왕국",
  "viking": "바이킹",
  "Exit App": "앱 종료",
  "Are you sure to exit from App?": "앱을 종료하시겠습니까?",
  "Yes": "예",
  "No": "아니요",
      "Select Languages": "언어 선택",
      "Save": "저장",
      "All Languages Voice Dictionary": "모든 언어 음성 사전",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "단어의 의미를 발견하고, 정확한 발음을 듣고, 우리의 음성 사전을 사용하여 사전을 확장하세요",
      "Skip": "건너뛰기",
      "Next": "다음",
      "Instant Translation": "즉각적인 번역",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "우리의 번역 기능을 사용하면 언어를 쉽게 이해하고 학습할 수 있습니다. 텍스트를 입력하면 몇 초 안에 명확한 번역을 얻을 수 있습니다",
      "Save Words": "단어 저장",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "학습하고자 하는 단어를 쉽게 저장하고 정리할 수 있습니다. 이 기능을 사용하면 개인 사전을 만들 수 있습니다",
      "Get Started": "시작",
      "ALL LANGUAGES DICTIONARY": "모든 언어 사전",
      "English": "영어",
      "Urdu": "우르두어",
      "Write Something....": "무언가 쓰기",
      "Features": "특징",
      "View All": "모두보기",
      "Translations": "번역",
      "History": "역사",
      "Share": "공유하기",
      "Home": "홈",
      "Setting": "설정",
      "Favourites": "즐겨찾기",
      "No Favourites available": "즐겨찾기가 없습니다",
      "No history available": "기록 없음"
    },
    "ms": {
  "Are you sure you want to delete?": "Adakah anda pasti mahu padam?",
  "No": "Tidak",
  "Yes": "Ya",
  "Delete": "Padam",
  "apple": "epal",
  "banana": "pisang",
  "cherry": "ceri",
  "date": "kurma",
  "elderberry": "elderberry",
  "fig": "sikoma",
  "grape": "anggur",
  "honeydew": "melun madu",
  "orange": "oren",
  "queen": "ratu",
  "kingdom": "kerajaan",
  "viking": "viking",
  "Exit App": "Keluar Aplikasi",
  "Are you sure to exit from App?": "Adakah anda pasti ingin keluar dari aplikasi?",
  "Yes": "Ya",
  "No": "Tidak",
      "Select Languages": "Pilih Bahasa",
      "Save": "Simpan",
      "All Languages Voice Dictionary": "Kamus Suara Semua Bahasa",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "Temukan makna kata, dengar sebutan yang tepat, dan kembangkan kamus anda dengan kamus suara kami",
      "Skip": "Langkau",
      "Next": "Seterusnya",
      "Instant Translation": "Terjemahan Segera",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "Fungsi terjemahan kami memudahkan anda memahami dan mempelajari bahasa. Hanya masukkan teks anda dan dapatkan terjemahan yang jelas dalam beberapa saat",
      "Save Words": "Simpan Kata",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "Dengan mudah menyimpan dan menyusun kata-kata yang ingin anda pelajari. Fungsi kami membolehkan anda membina kamus peribadi anda sendiri",
      "Get Started": "Bermula",
      "ALL LANGUAGES DICTIONARY": "KAMUS SEMUA BAHASA",
      "English": "Bahasa Inggeris",
      "Urdu": "Bahasa Urdu",
      "Write Something....": "Tulis Sesuatu",
      "Features": "Ciri-ciri",
      "View All": "Lihat Semua",
      "Translations": "Terjemahan",
      "History": "Sejarah",
      "Share": "Kongsi",
      "Home": "Laman Utama",
      "Setting": "Tetapan",
      "Favourites": "Kegemaran",
      "No Favourites available": "Tiada Kegemaran Tersedia",
      "No history available": "Tiada Sejarah Tersedia"
    },
    "pt": {
  "Are you sure you want to delete?": "Tem certeza de que deseja excluir?",
  "No": "Não",
  "Yes": "Sim",
  "Delete": "Excluir",
  "apple": "maçã",
  "banana": "banana",
  "cherry": "cereja",
  "date": "tâmara",
  "elderberry": "sabugueiro",
  "fig": "figo",
  "grape": "uva",
  "honeydew": "melão",
  "orange": "laranja",
  "queen": "rainha",
  "kingdom": "reino",
  "viking": "viking",
  "Exit App": "Sair do aplicativo",
  "Are you sure to exit from App?": "Tem certeza de que deseja sair do aplicativo?",
  "Yes": "Sim",
  "No": "Não",
      "Select Languages": "Selecionar Idiomas",
      "Save": "Salvar",
      "All Languages Voice Dictionary": "Dicionário De Voz De Todos Os Idiomas",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "Descubra o significado das palavras, ouça a pronúncia correta e expanda seu dicionário com nosso dicionário de voz",
      "Skip": "Pular",
      "Next": "Próximo",
      "Instant Translation": "Tradução Instantânea",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "Nossa função de tradução torna simples entender e aprender um idioma. Basta digitar seu texto e obter uma tradução clara em segundos",
      "Save Words": "Salvar Palavras",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "Salve e organize facilmente as palavras que deseja aprender. Nosso recurso permite que você construa seu próprio dicionário pessoal",
      "Get Started": "Começar",
      "ALL LANGUAGES DICTIONARY": "DICIONÁRIO DE TODOS OS IDIOMAS",
      "English": "Inglês",
      "Urdu": "Urdu",
      "Write Something....": "Escreva Algo",
      "Features": "Recursos",
      "View All": "Ver Todos",
      "Translations": "Traduções",
      "History": "Histórico",
      "Share": "Compartilhar",
      "Home": "Início",
      "Setting": "Configuração",
      "Favourites": "Favoritos",
      "No Favourites available": "Nenhum Favorito Disponível",
      "No history available": "Nenhum Histórico Disponível"
    },
    "ro": {
      "Select Languages": "Selectați Limbile",
      "Save": "Salvați",
      "All Languages Voice Dictionary": "Dicționar De Voce Pentru Toate Limbile",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "Descoperiți semnificația cuvintelor, auziți pronunția corectă și extindeți-vă dicționarul cu dicționarul nostru vocal",
      "Skip": "Sari",
      "Next": "Următorul",
      "Instant Translation": "Traducere Instantanee",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "Funcția noastră de traducere face simplă înțelegerea și învățarea limbii. Introduceți doar textul și obțineți o traducere clară în câteva secunde",
      "Save Words": "Salvați Cuvintele",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "Salvați și organizați cu ușurință cuvintele pe care doriți să le învățați. Funcția noastră vă permite să vă construiți propriul dicționar personal",
      "Get Started": "Începeți",
      "ALL LANGUAGES DICTIONARY": "DICȚIONARUL TUTUROR LIMBILOR",
      "English": "Engleză",
      "Urdu": "Urdu",
      "Write Something....": "Scrieți Ceva",
      "Features": "Funcții",
      "View All": "Vedeți Tot",
      "Translations": "Traduceri",
      "History": "Istorie",
      "Share": "Partajează",
      "Home": "Acasă",
      "Setting": "Setare",
      "Favourites": "Favorite",
      "No Favourites available": "Nu Sunt Disponibile Favorite",
      "No history available": "Nu Este Disponibil Istoric"
    },
    "ru": {
  "Are you sure you want to delete?": "Вы уверены, что хотите удалить?",
  "No": "Нет",
  "Yes": "Да",
  "Delete": "Удалить",
  "apple": "яблоко",
  "banana": "банан",
  "cherry": "вишня",
  "date": "финик",
  "elderberry": "бузина",
  "fig": "инжир",
  "grape": "виноград",
  "honeydew": "медовая дыня",
  "orange": "апельсин",
  "queen": "королева",
  "kingdom": "королевство",
  "viking": "викинг",
  "Exit App": "Выйти из приложения",
  "Are you sure to exit from App?": "Вы уверены, что хотите выйти из приложения?",
  "Yes": "Да",
  "No": "Нет",
      "Select Languages": "Выберите Языки",
      "Save": "Сохранить",
      "All Languages Voice Dictionary": "Голосовой Словарь Всех Языков",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "Узнайте значение слов, услышите правильное произношение и расширьте свой словарь с помощью нашего голосового словаря",
      "Skip": "Пропустить",
      "Next": "Далее",
      "Instant Translation": "Мгновенный Перевод",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "Функция перевода позволяет легко понять и выучить язык. Просто введите свой текст и получите точный перевод за считанные секунды",
      "Save Words": "Сохранить Слова",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "Легко сохраняйте и организуйте слова, которые вы хотите выучить. Наша функция позволяет вам создавать собственный личный словарь",
      "Get Started": "Начать",
      "ALL LANGUAGES DICTIONARY": "СЛОВАРЬ ВСЕХ ЯЗЫКОВ",
      "English": "Английский",
      "Urdu": "Урду",
      "Write Something....": "Напишите Что-нибудь",
      "Features": "Функции",
      "View All": "Посмотреть Все",
      "Translations": "Переводы",
      "History": "История",
      "Share": "Поделиться",
      "Home": "Главная",
      "Setting": "Настройка",
      "Favourites": "Избранное",
      "No Favourites available": "Нет Избранного",
      "No history available": "Нет Истории"
    },
    "es": {
  "Are you sure you want to delete?": "¿Estás seguro de que quieres eliminar?",
  "No": "No",
  "Yes": "Sí",
  "Delete": "Eliminar",
  "apple": "manzana",
  "banana": "plátano",
  "cherry": "cereza",
  "date": "dátil",
  "elderberry": "saúco",
  "fig": "higo",
  "grape": "uva",
  "honeydew": "melón",
  "orange": "naranja",
  "queen": "reina",
  "kingdom": "reino",
  "viking": "vikingo",
  "Exit App": "Salir de la aplicación",
  "Are you sure to exit from App?": "¿Estás seguro de que deseas salir de la aplicación?",
  "Yes": "Sí",
  "No": "No",
      "Select Languages": "Seleccionar Idiomas",
      "Save": "Guardar",
      "All Languages Voice Dictionary": "Diccionario De Voz De Todos Los Idiomas",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "Descubra el significado de las palabras, escuche la pronunciación precisa y amplíe su diccionario con nuestro diccionario de voz",
      "Skip": "Omitir",
      "Next": "Siguiente",
      "Instant Translation": "Traducción Instantánea",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "Nuestra función de traducción hace que sea sencillo entender y aprender idiomas. Simplemente ingrese su texto y obtenga una traducción clara en segundos",
      "Save Words": "Guardar Palabras",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "Guarde y organice fácilmente las palabras que desea aprender. Nuestra función le permite construir su propio diccionario personal",
      "Get Started": "Comenzar",
      "ALL LANGUAGES DICTIONARY": "DICCIONARIO DE TODOS LOS IDIOMAS",
      "English": "Inglés",
      "Urdu": "Urdu",
      "Write Something....": "Escribir Algo",
      "Features": "Características",
      "View All": "Ver Todo",
      "Translations": "Traducciones",
      "History": "Historial",
      "Share": "Compartir",
      "Home": "Inicio",
      "Setting": "Configuración",
      "Favourites": "Favoritos",
      "No Favourites available": "No Hay Favoritos Disponibles",
      "No history available": "No Hay Historial Disponible"
    },
    "ta": {
      "Select Languages": "மொழிகளைத் தேர்ந்தெடுக்கவும்",
      "Save": "சேமிக்க",
      "All Languages Voice Dictionary": "அனைத்து மொழிகளின் குரல் அகராதி",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "சொற்களின் அர்த்தத்தை கண்டறியவும், சரியான உச்சரிப்பைக் கேட்கவும், எங்கள் குரல் அகராதியுடன் உங்கள் அகராதியை விரிவுபடுத்தவும்",
      "Skip": "தவிர்க்கவும்",
      "Next": "அடுத்தது",
      "Instant Translation": "உடனடி மொழிபெயர்ப்பு",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "எங்கள் மொழிபெயர்ப்பு அம்சம் மொழியை புரிந்து கொள்ளவும் கற்றுக்கொள்ளவும் எளிமையாக ஆகும். உங்கள் உரையை உள்ளீடு செய்க, சில விநாடிகளில் தெளிவான மொழிபெயர்ப்பைப் பெறுங்கள்",
      "Save Words": "சொற்களைச் சேமிக்கவும்",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "நீங்கள் கற்றுக்கொள்ள விரும்பும் சொற்களை எளிதாகச் சேமிக்கவும் ஒழுங்குபடுத்தவும். எங்கள் அம்சம் உங்கள் சொந்த தனிப்பட்ட அகராதியை உருவாக்க உங்களை அனுமதிக்கிறது",
      "Get Started": "தொடங்கவும்",
      "ALL LANGUAGES DICTIONARY": "அனைத்து மொழிகளின் அகராதி",
      "English": "ஆங்கிலம்",
      "Urdu": "உருது",
      "Write Something....": "ஏதாவது எழுதுங்கள்",
      "Features": "அம்சங்கள்",
      "View All": "அனைத்தையும் காண்க",
      "Translations": "மொழிபெயர்ப்புகள்",
      "History": "வரலாறு",
      "Share": "பகிர்",
      "Home": "முகப்பு",
      "Setting": "அமைப்பு",
      "Favourites": "பிடித்தவை",
      "No Favourites available": "பிடித்தவை இல்லை",
      "No history available": "வரலாறு இல்லை"
    },
    "th": {
  "Are you sure you want to delete?": "คุณแน่ใจว่าต้องการลบใช่หรือไม่?",
  "No": "ไม่",
  "Yes": "ใช่",
  "Delete": "ลบ",
  "apple": "แอปเปิ้ล",
  "banana": "กล้วย",
  "cherry": "เชอร์รี่",
  "date": "อินทผาลัม",
  "elderberry": "เบอร์รี่เอลเดอร์",
  "fig": "มะเดื่อ",
  "grape": "องุ่น",
  "honeydew": "เมลอน",
  "orange": "ส้ม",
  "queen": "ราชินี",
  "kingdom": "อาณาจักร",
  "viking": "ไวกิ้ง",
  "Exit App": "ออกจากแอป",
  "Are you sure to exit from App?": "คุณแน่ใจหรือไม่ว่าต้องการออกจากแอป?",
  "Yes": "ใช่",
  "No": "ไม่",
      "Select Languages": "เลือกภาษา",
      "Save": "บันทึก",
      "All Languages Voice Dictionary": "พจนานุกรมเสียงทุกภาษา",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "ค้นหาความหมายของคำ ฟังการออกเสียงที่ถูกต้อง และขยายพจนานุกรมของคุณด้วยพจนานุกรมเสียงของเรา",
      "Skip": "ข้าม",
      "Next": "ถัดไป",
      "Instant Translation": "การแปลทันที",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "ฟังก์ชันการแปลของเราทำให้เข้าใจและเรียนรู้ภาษาได้ง่าย เพียงป้อนข้อความของคุณและรับการแปลที่ชัดเจนในไม่กี่วินาที",
      "Save Words": "บันทึกคำ",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "บันทึกและจัดระเบียบคำที่คุณต้องการเรียนรู้อย่างง่ายดาย ฟีเจอร์ของเราช่วยให้คุณสร้างพจนานุกรมส่วนตัวของคุณเองได้",
      "Get Started": "เริ่มต้น",
      "ALL LANGUAGES DICTIONARY": "พจนานุกรมทุกภาษา",
      "English": "ภาษาอังกฤษ",
      "Urdu": "อูรดู",
      "Write Something....": "เขียนอะไรบางอย่าง",
      "Features": "คุณสมบัติ",
      "View All": "ดูทั้งหมด",
      "Translations": "การแปล",
      "History": "ประวัติ",
      "Share": "แบ่งปัน",
      "Home": "หน้าแรก",
      "Setting": "ตั้งค่า",
      "Favourites": "รายการโปรด",
      "No Favourites available": "ไม่มีรายการโปรดที่พร้อมใช้งาน",
      "No history available": "ไม่มีประวัติที่ใช้ได้"
    },
    "tr": {
  "Are you sure you want to delete?": "Silmek istediğinizden emin misiniz?",
  "No": "Hayır",
  "Yes": "Evet",
  "Delete": "Sil",
  "apple": "elma",
  "banana": "muz",
  "cherry": "kiraz",
  "date": "hurma",
  "elderberry": "çörek otu",
  "fig": "incir",
  "grape": "üzüm",
  "honeydew": "bal kavun",
  "orange": "portakal",
  "queen": "kraliçe",
  "kingdom": "krallık",
  "viking": "vikings",
  "Exit App": "Uygulamayı Kapat",
  "Are you sure to exit from App?": "Uygulamadan çıkmak istediğinize emin misiniz?",
  "Yes": "Evet",
  "No": "Hayır",
      "Select Languages": "Dilleri Seç",
      "Save": "Kaydet",
      "All Languages Voice Dictionary": "Tüm Dillerin Sesli Sözlüğü",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "Kelime anlamlarını keşfedin, doğru telaffuzu duyun ve sesli sözlüğümüzle kelime dağarcığınızı genişletin",
      "Skip": "Atla",
      "Next": "Sonraki",
      "Instant Translation": "Anında Çeviri",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "Çeviri özelliğimiz, dili anlamayı ve öğrenmeyi kolaylaştırır. Tek yapmanız gereken metninizi girmek ve birkaç saniye içinde net bir çeviri almak",
      "Save Words": "Kelime Kaydet",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "Öğrenmek istediğiniz kelimeleri kolayca kaydedin ve düzenleyin. Bu özellik, kendi kişisel sözlüğünüzü oluşturmanıza olanak tanır",
      "Get Started": "Başlayın",
      "ALL LANGUAGES DICTIONARY": "TÜM DİLLERİN SÖZLÜĞÜ",
      "English": "İngilizce",
      "Urdu": "Urdu",
      "Write Something....": "Bir şey yaz",
      "Features": "Özellikler",
      "View All": "Hepsini Gör",
      "Translations": "Çeviriler",
      "History": "Geçmiş",
      "Share": "Paylaş",
      "Home": "Ana Sayfa",
      "Setting": "Ayarlar",
      "Favourites": "Favoriler",
      "No Favourites available": "Favori Yok",
      "No history available": "Geçmiş Yok"
    },
    "ur": {
  "Are you sure you want to delete?": "کیا آپ کو یقین ہے کہ آپ حذف کرنا چاہتے ہیں؟",
  "No": "نہیں",
  "Yes": "جی ہاں",
  "Delete": "حذف کریں",
  "apple": "سیب",
  "banana": "کیلا",
  "cherry": "چیری",
  "date": "کھجور",
  "elderberry": "بیر",
  "fig": "انجیر",
  "grape": "انگور",
  "honeydew": "ملاکا",
  "orange": "سنترہ",
  "queen": "ملکہ",
  "kingdom": "بادشاہت",
  "viking": "وائیکنگ",
  "Exit App": "ایپ بند کریں",
  "Are you sure to exit from App?": "کیا آپ واقعی ایپ سے باہر نکلنا چاہتے ہیں؟",
  "Yes": "جی ہاں",
  "No": "نہیں",
      "Select Languages": "زبانیں منتخب کریں",
      "Save": "محفوظ کریں",
      "All Languages Voice Dictionary": "تمام زبانوں کی وائس ڈکشنری",
      "Discover words meaning, hear accurate pronounciation, and expand your dictionary with our voice dictionary": "الفاظ کا مطلب دریافت کریں، صحیح تلفظ سنیں، اور ہماری وائس ڈکشنری کے ساتھ اپنے ڈکشنری کو وسعت دیں",
      "Skip": "چھوڑیں",
      "Next": "اگلا",
      "Instant Translation": "فوری ترجمہ",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "ہمارا ترجمہ فیچر زبان کو سمجھنا اور سیکھنا آسان بناتا ہے۔ بس اپنا متن درج کریں اور چند سیکنڈ میں واضح ترجمہ حاصل کریں",
      "Save The Words": "الفاظ محفوظ کریں",
      "Save Words": "الفاظ محفوظ کریں",
      "Easily save and organize words you want to learn Our feature lets you build your own personal dictionary": "آسانی سے ان الفاظ کو محفوظ کریں اور ترتیب دیں جو آپ سیکھنا چاہتے ہیں۔ ہمارا فیچر آپ کو اپنی ذاتی ڈکشنری بنانے دیتا ہے",
      "Get started": "شروع کریں",
      "ALL LANGUAGES DICTIONARY": "تمام زبانوں کی ڈکشنری",
      "English": "انگریزی",
      "Urdu": "اردو",
      "Write Something....": "کچھ لکھیں",
      "Features": "خصوصیات",
      "View all": "سب دیکھیں",
      "Translation": "ترجمے",
      "History": "تاریخ",
      "Share": "شئیر کریں",
      "Home": "ہوم",
      "Setting": "ترتیب",
      "Favourites": "پسندیدہ",
      "No Favorites available": "کوئی پسندیدہ دستیاب نہیں ہے",
      "No history available": "کوئی تاریخ دستیاب نہیں ہے",
      "Translations":"ترجمے",
      "Notifications":"اطلاعات",
      "Settings":"ترتیبات",
    },
    "fa":{
  "Are you sure you want to delete?": "آیا مطمئن هستید که می‌خواهید حذف کنید؟",
  "No": "خیر",
  "Yes": "بله",
  "Delete": "حذف",
  "apple": "سیب",
  "banana": "موز",
  "cherry": "گیلاس",
  "date": "خرما",
  "elderberry": "بري زغال اخته",
  "fig": "انجیر",
  "grape": "انگور",
  "honeydew": "خربزه",
  "orange": "پرتقال",
  "queen": "ملکه",
  "kingdom": "پادشاهی",
  "viking": "وایکینگ",
  "Exit App": "خروج از اپلیکیشن",
  "Are you sure to exit from App?": "آیا مطمئن هستید که می‌خواهید از اپلیکیشن خارج شوید؟",
  "Yes": "بله",
  "No": "خیر",
      "Select Languages": "زبان‌ها را انتخاب کنید",
      "Save": "ذخیره",
      "All Languages Voice Dictionary": "واژه‌نامه صوتی همه زبان‌ها",
    "Discover words meaning, hear accurate pronounciations and expand your dictionary with our voice dictionary": "معنی کلمات را کشف کنید، تلفظ دقیق را بشنوید و دایره واژگان خود را با واژه‌نامه صوتی ما گسترش دهید",
      "Skip": "رد کردن",
      "Next": "بعدی",
      "Instant Translation": "ترجمه آنی",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "ویژگی ترجمه ما فهم و یادگیری زبان را ساده می‌کند. فقط متن خود را وارد کنید و در عرض چند ثانیه ترجمه واضحی دریافت کنید",
      "Save Words": "ذخیره کلمات",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "به راحتی کلمات مورد نظر خود را ذخیره و سازماندهی کنید. ویژگی ما به شما امکان می‌دهد دیکشنری شخصی خود را بسازید",
      "Get Started": "شروع کنید",
      "ALL LANGUAGES DICTIONARY": "واژه‌نامه همه زبان‌ها",
      "English": "انگلیسی",
      "Urdu": "اردو",
      "Write Something....": "چیزی بنویسید",
      "Features": "ویژگی‌ها",
      "View All": "مشاهده همه",
      "Translations": "ترجمه‌ها",
      "History": "تاریخچه",
      "Share": "اشتراک‌گذاری",
      "Home": "خانه",
      "Setting": "تنظیمات",
      "Favourites": "علاقه‌مندی‌ها",
      "No Favourites available": "علاقه‌مندی در دسترس نیست",
      "No history available": "تاریخچه در دسترس نیست"
    },
    "vi":{
  "Are you sure you want to delete?": "Bạn có chắc chắn muốn xóa không?",
  "No": "Không",
  "Yes": "Có",
  "Delete": "Xóa",
  "apple": "táo",
  "banana": "chuối",
  "cherry": "anh đào",
  "date": "chà là",
  "elderberry": "quả cơm cháy",
  "fig": "sung",
  "grape": "nho",
  "honeydew": "dưa mật",
  "orange": "cam",
  "queen": "nữ hoàng",
  "kingdom": "vương quốc",
  "viking": "người Viking",
  "Exit App": "Thoát ứng dụng",
  "Are you sure to exit from App?": "Bạn có chắc chắn muốn thoát khỏi ứng dụng không?",
  "Yes": "Có",
  "No": "Không",
      "Select Languages": "Chọn Ngôn Ngữ",
      "Save": "Lưu",
      "All Languages Voice Dictionary": "Từ Điển Giọng Nói Tất Cả Các Ngôn Ngữ",
      "Discover words meaning, hear accurate pronunciation, and expand your dictionary with our voice dictionary": "Khám phá ý nghĩa của từ, nghe phát âm chính xác và mở rộng từ điển của bạn với từ điển giọng nói của chúng tôi",
      "Skip": "Bỏ Qua",
      "Next": "Tiếp Theo",
      "Instant Translation": "Dịch Ngay Lập Tức",
      "Our Translation feature makes it simple to understand and learn language. Just enter your text and get a clear translation in seconds": "Chức năng dịch của chúng tôi giúp bạn dễ dàng hiểu và học ngôn ngữ. Chỉ cần nhập văn bản của bạn và nhận bản dịch rõ ràng trong vài giây",
      "Save Words": "Lưu Từ",
      "Easily save and organize words you want to learn. Our feature lets you build your own personal dictionary": "Dễ dàng lưu và tổ chức các từ bạn muốn học. Tính năng của chúng tôi cho phép bạn tạo từ điển cá nhân của riêng mình",
      "Get Started": "Bắt Đầu",
      "ALL LANGUAGES DICTIONARY": "TỪ ĐIỂN TẤT CẢ CÁC NGÔN NGỮ",
      "English": "Tiếng Anh",
      "Urdu": "Tiếng Urdu",
      "Write Something....": "Viết Gì Đó",
      "Features": "Tính Năng",
      "View All": "Xem Tất Cả",
      "Translations": "Dịch",
      "History": "Lịch Sử",
      "Share": "Chia Sẻ",
      "Home": "Trang Chủ",
      "Setting": "Cài Đặt",
      "Favourites": "Yêu Thích",
      "No Favourites available": "Không có yêu thích",
      "No history available": "Không có lịch sử"
    }


  };
}