class StringConstants {

  static const List<String> languages = [
    'English',
    'Spanish',
    'French',
    'Russian',
    'German',
    'Italian',
    'Japanese',
    'Arabic',
    'Korean',
    'Urdu',
    'Pashto',
    'Portuguese',
    'Chinese',
    'Turkish',
    'Vietnamese',
    'Thai',
    'Polish',
    'Dutch',
    'Swedish',
    'Danish',
    'Norwegian',
    'Finnish',
    'Hungarian',
    'Czech',
    'Slovak',
    'Romanian',
    'Bulgarian',
    'Greek',
    'Hebrew',
    'Swahili',
    'Malay',
    'Indonesian',
    'Lithuanian',
    'Latvian',
    'Estonian',
    'Icelandic',
    'Irish',
    'Catalan',
    'Basque',
    'Galician',

  ];
}